const prisma = require('../config/db');

// @desc    Get products that are at or below their minimum stock level
// @route   GET /api/purchase-requests/low-stock
// @access  Private (All authenticated users)
exports.getLowStock = async (req, res) => {
    try {
        // Fetch products and filter those needing restock
        const products = await prisma.product.findMany({
            select: { id: true, name: true, sku: true, currentStock: true, minStockLevel: true }
        });

        const lowStockProducts = products.filter(p => p.currentStock <= p.minStockLevel);

        res.status(200).json(lowStockProducts);
    } catch (error) {
        console.error("Error fetching low stock:", error);
        res.status(500).json({ message: 'Server error fetching low stock' });
    }
};

// @desc    Create a new purchase request
// @route   POST /api/purchase-requests
// @access  Private (Staff, Manager, Admin)
exports.createRequest = async (req, res) => {
    try {
        const { productId, quantity, reason } = req.body;
        const userId = req.user.userId; // From JWT

        const request = await prisma.purchaseRequest.create({
            data: { productId, userId, quantity, reason }
        });

        res.status(201).json({ message: 'Purchase request submitted', request });
    } catch (error) {
        res.status(500).json({ message: 'Server error creating request' });
    }
};

// @desc    Approve or Reject a purchase request
// @route   PATCH /api/purchase-requests/:id
// @access  Private (Manager or Admin ONLY)
exports.updateRequestStatus = async (req, res) => {
    try {
        const { id } = req.params;
        const { status } = req.body; // 'APPROVED' or 'REJECTED'
        const managerId = req.user.userId;

        if (!['APPROVED', 'REJECTED'].includes(status)) {
            return res.status(400).json({ message: 'Invalid status' });
        }

        // --- PRISMA TRANSACTION ---
        // If approved, we must update the request, increase stock, AND log it.
        const result = await prisma.$transaction(async (tx) => {
            const request = await tx.purchaseRequest.update({
                where: { id },
                data: { status, managerId }
            });

            if (status === 'APPROVED') {
                // 1. Update Product Stock
                await tx.product.update({
                    where: { id: request.productId },
                    data: { currentStock: { increment: request.quantity } }
                });

                // 2. Create Audit Log (Auto-generated by the system)
                await tx.inventoryHistory.create({
                    data: {
                        productId: request.productId,
                        userId: managerId,
                        type: 'IN',
                        quantity: request.quantity,
                        reason: `Purchase Request Approved (ID: ${request.id})`
                    }
                });
            }
            return request;
        });

        res.status(200).json({ message: `Request ${status.toLowerCase()} successfully`, data: result });
    } catch (error) {
        console.error("Error updating request:", error);
        res.status(500).json({ message: 'Server error updating request' });
    }
};


// @desc    Get all purchase requests
// @route   GET /api/purchase-requests
// @access  Private
exports.getAllRequests = async (req, res) => {
    try {
        const requests = await prisma.purchaseRequest.findMany({
            include: {
                product: { select: { name: true, sku: true, currentStock: true } },
                user: { select: { name: true } }
            },
            orderBy: { createdAt: 'desc' }
        });
        res.status(200).json(requests);
    } catch (error) {
        console.error("Error fetching requests:", error);
        res.status(500).json({ message: 'Server error fetching requests' });
    }
};